#!/usr/bin/env python3
"""Aggregate the crowd-density ablation results into one table.

Reads results/warehouse_ablation/<N>_<r>.json (scand_metrics JSON summaries, one
per trial r at crowd size N, written by run_ablation.sh) and emits ONE row per
density level N — Succ. = successes/trials, remaining columns mean$\\pm$std over
the trials at that N. Density = actors / 1214 m^2 navigable area (matches
density_sweep.py). Skips <N>_<r>_evo_log.json.

Usage: python3 gen_ablation_table.py [results_dir]
Writes <results_dir>/ablation_table.tex and prints a plaintext preview.
"""
import glob
import json
import os
import re
import sys
from collections import defaultdict
from statistics import mean, pstdev

RESULTS_DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "results", "warehouse_ablation")

USABLE_AREA_M2 = 1214.0   # warehouse navigable floor area (matches density_sweep.py)

# <N>_<r>.json  (N = crowd size, r = trial); exclude the *_evo_log.json companions
TRIAL_RE = re.compile(r"^(\d+)_(\d+)\.json$")


def parse_metrics_json(path):
    try:
        d = json.loads(open(path, errors="replace").read())
    except (json.JSONDecodeError, OSError):
        return None
    if d.get("node") != "scand_metrics":
        return None
    return {
        "succ":        bool(d.get("success")),
        "progress":    d.get("path_progress_pct"),
        "duration":    d.get("duration_s"),
        "path_length": d.get("path_length_m"),
        "coll":        d.get("collisions"),
        "min_clr":     d.get("min_human_clearance_m"),
        "intim_pct":   d.get("intim_pct"),
        "pers_pct":    d.get("pers_pct"),
        "social_pct":  d.get("social_pct"),
        "p_int":       d.get("p_int"),
    }


def ms(vals, prec=1):
    """mean$\\pm$std over the non-None values, as 'm$\\pm$s' (or '--')."""
    xs = [v for v in vals if v is not None]
    if not xs:
        return "--"
    m = mean(xs)
    s = pstdev(xs) if len(xs) > 1 else 0.0
    return f"{m:.{prec}f}$\\pm${s:.{prec}f}"


def ms_plain(vals, prec=1):
    xs = [v for v in vals if v is not None]
    if not xs:
        return "--"
    m = mean(xs)
    s = pstdev(xs) if len(xs) > 1 else 0.0
    return f"{m:.{prec}f}±{s:.{prec}f}"


def main():
    runs = defaultdict(list)   # N -> [metrics dict, ...]
    for f in sorted(glob.glob(os.path.join(RESULTS_DIR, "*.json"))):
        m = TRIAL_RE.match(os.path.basename(f))
        if not m:
            continue
        d = parse_metrics_json(f)
        if d is not None:
            runs[int(m.group(1))].append(d)

    if not runs:
        print(f"No parseable <N>_<r>.json trials in {RESULTS_DIR}", file=sys.stderr)
        sys.exit(1)

    Ns = sorted(runs)

    # ---- LaTeX table ----
    lines = [
        "% Auto-generated by gen_ablation_table.py",
        "% Crowd-density ablation (warehouse, MULTICAM 360 detection); mean$\\pm$std over trials.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Social-navigation metrics vs.\\ crowd density (warehouse, "
        "MULTICAM 360$^\\circ$ detection). Density = actors\\,/\\,1214\\,m$^2$ navigable "
        "area; Succ.\\ = successes/trials; other columns mean$\\pm$std over trials.}",
        "\\label{tab:density_ablation}",
        "\\begin{tabular}{cccccccccc}",
        "\\toprule",
        "Actors & Density & Succ. & Time\\,[s] & Path\\,[m] & Coll & MinClr\\,[m] & "
        "Intim\\,\\% & Pers\\,\\% & Social\\,\\% \\\\",
        "\\midrule",
    ]
    for N in Ns:
        rs = runs[N]
        n = len(rs)
        nsucc = sum(1 for r in rs if r["succ"])
        row = " & ".join([
            str(N),
            f"{N / USABLE_AREA_M2:.4f}",
            f"{nsucc}/{n}",
            ms([r["duration"] for r in rs], 0),
            ms([r["path_length"] for r in rs], 1),
            ms([r["coll"] for r in rs], 1),
            ms([r["min_clr"] for r in rs], 2),
            ms([r["intim_pct"] for r in rs], 1),
            ms([r["pers_pct"] for r in rs], 1),
            ms([r["social_pct"] for r in rs], 1),
        ])
        lines.append(row + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]

    out = os.path.join(RESULTS_DIR, "ablation_table.tex")
    open(out, "w").write("\n".join(lines))

    # ---- plaintext preview ----
    total = sum(len(v) for v in runs.values())
    print(f"Parsed {total} trials across {len(Ns)} density levels "
          f"(N={Ns}) in {RESULTS_DIR}\n")
    hdr = (f"{'N':>3} {'dens':>7} {'succ':>6} {'time[s]':>12} {'path[m]':>12} "
           f"{'coll':>9} {'minClr':>11} {'social%':>11}")
    print(hdr)
    print("-" * len(hdr))
    for N in Ns:
        rs = runs[N]
        n = len(rs)
        nsucc = sum(1 for r in rs if r["succ"])
        print(f"{N:>3} {N/USABLE_AREA_M2:>7.4f} {f'{nsucc}/{n}':>6} "
              f"{ms_plain([r['duration'] for r in rs],0):>12} "
              f"{ms_plain([r['path_length'] for r in rs],1):>12} "
              f"{ms_plain([r['coll'] for r in rs],1):>9} "
              f"{ms_plain([r['min_clr'] for r in rs],2):>11} "
              f"{ms_plain([r['social_pct'] for r in rs],1):>11}")
    print(f"\nWrote {out}")


if __name__ == "__main__":
    main()
