#!/usr/bin/env python3
"""Parse results/factory_trials/plan*_trial*_metrics.json (scand_metrics JSON
summaries from run_trials.sh) and emit ONE LaTeX results table in the
sample_table.tex format: one row per mission plan, aggregating all trials
(Succ. = successes/trials, remaining columns mean$\\pm$std over trials).
A row is emitted for every plan file under factory_mission_plans/, so the
table always has one line per plan ("--" columns until trials are logged).

Usage: python3 gen_trials_table.py [results_dir]
Writes <results_dir>/results_table.tex and prints a plaintext preview.
"""
import glob
import json
import os
import re
import sys
from collections import defaultdict
from statistics import mean, pstdev

RESULTS_DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "results", "factory_trials")

PLANS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "factory_mission_plans")


def parse_metrics_json(path):
    try:
        d = json.loads(open(path, errors="replace").read())
    except (json.JSONDecodeError, OSError):
        return None
    if d.get("node") != "scand_metrics":
        return None
    return {
        "duration":    d.get("duration_s"),
        "path_length": d.get("path_length_m"),
        "coll":        d.get("collisions"),
        "succ":        bool(d.get("success")),
        "progress":    d.get("path_progress_pct"),
        "intim_pct":   d.get("intim_pct"),
        "pers_pct":    d.get("pers_pct"),
        "social_pct":  d.get("social_pct"),
        "p_int":       d.get("p_int"),
        "min_clr":     d.get("min_human_clearance_m"),
    }


def fmt(vals, prec=1):
    vals = [v for v in vals if v is not None]
    if not vals:
        return "--"
    if len(vals) == 1:
        return f"{vals[0]:.{prec}f}"
    return f"{mean(vals):.{prec}f}$\\pm${pstdev(vals):.{prec}f}"


def main():
    runs = defaultdict(list)  # plan -> [dict,...]
    for f in sorted(glob.glob(os.path.join(RESULTS_DIR, "plan*_trial*_metrics.json"))):
        m = re.search(r"plan(\d+)_trial(\d+)", os.path.basename(f))
        if not m:
            continue
        d = parse_metrics_json(f)
        if d:
            runs[m.group(1)].append(d)

    # one table row per plan file, whether or not any trial is logged yet
    plans = sorted({re.search(r"factory_mission_(\d+)\.txt", f).group(1)
                    for f in glob.glob(os.path.join(PLANS_DIR, "factory_mission_*.txt"))}
                   | set(runs))
    if not plans:
        print(f"No plans in {PLANS_DIR} and no parseable _metrics.json in {RESULTS_DIR}",
              file=sys.stderr)
        sys.exit(1)

    n_per = max((len(v) for v in runs.values()), default=0)

    # ---- LaTeX (sample_table.tex format: one row per mission, all trials) ----
    lines = []
    lines.append("% Auto-generated by gen_trials_table.py")
    lines.append("\\begin{table}[!ht]")
    lines.append("\\centering")
    lines.append("\\caption{Per-mission metrics (populated warehouse, "
                 f"{n_per} runs per mission; mean$\\pm$std over runs). "
                 "Intim/Pers/Social are the fraction of ticks with the nearest pedestrian "
                 "inside Hall's intimate ($<$0.45\\,m), personal ($<$1.2\\,m), and social "
                 "($<$3.6\\,m) zones; $P_{\\mathrm{int}}=\\sum\\max(0,\\,1.2-\\mathrm{clr})$.}")
    lines.append("\\label{tab:factory_missions}")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("\\begin{tabular}{lcccccccccc}")
    lines.append("\\toprule")
    lines.append("Mission & Succ. & Route \\% & Coll. & Path [m] & Time [s] & "
                 "Intim \\% & Pers \\% & Social \\% & $P_{\\mathrm{int}}$ & Min clr [m] \\\\")
    lines.append("\\midrule")
    for p in plans:
        rs = runs.get(p, [])
        n = len(rs)
        succ = f"{sum(1 for r in rs if r['succ'])}/{n}" if n else "--"
        row = " & ".join([
            f"M{int(p)}",
            succ,
            fmt([r.get("progress") for r in rs], 0),
            fmt([r["coll"] for r in rs], 1),
            fmt([r["path_length"] for r in rs], 1),
            fmt([r["duration"] for r in rs], 0),
            fmt([r["intim_pct"] for r in rs], 1),
            fmt([r["pers_pct"] for r in rs], 1),
            fmt([r["social_pct"] for r in rs], 1),
            fmt([r["p_int"] for r in rs], 1),
            fmt([r["min_clr"] for r in rs], 2),
        ])
        lines.append(row + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    tex = "\n".join(lines) + "\n"

    os.makedirs(RESULTS_DIR, exist_ok=True)
    out = os.path.join(RESULTS_DIR, "results_table.tex")
    open(out, "w").write(tex)

    # ---- plaintext preview ----
    print(f"Parsed {sum(len(v) for v in runs.values())} runs across "
          f"{sum(1 for p in plans if runs.get(p))}/{len(plans)} plans.\n")
    hdr = (f"{'Plan':6} {'Succ':6} {'Route%':8} {'Coll':9} {'Path':12} {'Time':10} "
           f"{'Intim%':9} {'Pers%':9} {'Social%':10} {'Pint':10} {'MinClr':10}")
    print(hdr)
    print("-" * len(hdr))
    pt = lambda s: s.replace("$\\pm$", "+-")
    for p in plans:
        rs = runs.get(p, [])
        n = len(rs)
        succ = f"{sum(1 for r in rs if r['succ'])}/{n}" if n else "--"
        print(f"M{int(p):<5} {succ:6} "
              f"{pt(fmt([r.get('progress') for r in rs], 0)):8} "
              f"{pt(fmt([r['coll'] for r in rs], 1)):9} "
              f"{pt(fmt([r['path_length'] for r in rs], 1)):12} "
              f"{pt(fmt([r['duration'] for r in rs], 0)):10} "
              f"{pt(fmt([r['intim_pct'] for r in rs], 1)):9} "
              f"{pt(fmt([r['pers_pct'] for r in rs], 1)):9} "
              f"{pt(fmt([r['social_pct'] for r in rs], 1)):10} "
              f"{pt(fmt([r['p_int'] for r in rs], 1)):10} "
              f"{pt(fmt([r['min_clr'] for r in rs], 2)):10}")
    print(f"\nWrote {out}")


if __name__ == "__main__":
    main()
